services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: karma8
      POSTGRES_USER: karma8
      POSTGRES_PASSWORD: karma8
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/postgres/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres:
